"""travel shopper tables

Revision ID: 3627d5e550ba
Revises: 713f031bd6f4
Create Date: 2026-09-28 23:09:20.883463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3627d5e550ba'
down_revision: Union[str, Sequence[str], None] = '713f031bd6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('suppliers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_searches_conversation_id'), 'shop_searches', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shop_searches_property_id'), 'shop_searches', ['property_id'], unique=False)
    op.create_table('shop_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('offer', sa.JSON(), nullable=False),
    sa.Column('recheck', sa.JSON(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('terms_hash', sa.String(length=64), nullable=False),
    sa.Column('compared', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['shop_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_quotes_conversation_id'), 'shop_quotes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shop_quotes_property_id'), 'shop_quotes', ['property_id'], unique=False)
    op.create_table('shop_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('supplier', sa.String(length=40), nullable=False),
    sa.Column('supplier_reference', sa.String(length=120), nullable=True),
    sa.Column('hotel_confirmation', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['shop_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_shop_bookings_conversation_id'), 'shop_bookings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shop_bookings_property_id'), 'shop_bookings', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_bookings_property_id'), table_name='shop_bookings')
    op.drop_index(op.f('ix_shop_bookings_conversation_id'), table_name='shop_bookings')
    op.drop_table('shop_bookings')
    op.drop_index(op.f('ix_shop_quotes_property_id'), table_name='shop_quotes')
    op.drop_index(op.f('ix_shop_quotes_conversation_id'), table_name='shop_quotes')
    op.drop_table('shop_quotes')
    op.drop_index(op.f('ix_shop_searches_property_id'), table_name='shop_searches')
    op.drop_index(op.f('ix_shop_searches_conversation_id'), table_name='shop_searches')
    op.drop_table('shop_searches')
    # ### end Alembic commands ###
