"""knowledge version

Revision ID: 713f031bd6f4
Revises: 8c5bac874739
Create Date: 2026-09-28 22:49:35.380318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713f031bd6f4'
down_revision: Union[str, Sequence[str], None] = '8c5bac874739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('knowledge_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'knowledge_version')
    # ### end Alembic commands ###
