"""staff typing until

Revision ID: adcb36a4da20
Revises: c899848119f8
Create Date: 2026-09-28 22:08:25.706972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcb36a4da20'
down_revision: Union[str, Sequence[str], None] = 'c899848119f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('staff_typing_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'staff_typing_until')
    # ### end Alembic commands ###
