"""initial schema

Revision ID: c899848119f8
Revises: 
Create Date: 2026-09-28 15:03:39.899769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c899848119f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('connector', sa.JSON(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_properties_org_id'), 'properties', ['org_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_table('hotel_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'key', 'language')
    )
    op.create_index(op.f('ix_hotel_facts_property_id'), 'hotel_facts', ['property_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_property_id'), 'knowledge_chunks', ['property_id'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoffs_conversation_id'), 'handoffs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_handoffs_property_id'), 'handoffs', ['property_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_property_id'), 'messages', ['property_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('terms_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_conversation_id'), 'quotes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_quotes_property_id'), 'quotes', ['property_id'], unique=False)
    op.create_table('booking_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_booking_intents_conversation_id'), 'booking_intents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_booking_intents_property_id'), 'booking_intents', ['property_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('timings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'request_id')
    )
    op.create_index(op.f('ix_turns_conversation_id'), 'turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_turns_property_id'), 'turns', ['property_id'], unique=False)
    op.create_table('effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['booking_intents.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effects_intent_id'), 'effects', ['intent_id'], unique=False)
    op.create_index(op.f('ix_effects_property_id'), 'effects', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_effects_property_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_intent_id'), table_name='effects')
    op.drop_table('effects')
    op.drop_index(op.f('ix_turns_property_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_conversation_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_booking_intents_property_id'), table_name='booking_intents')
    op.drop_index(op.f('ix_booking_intents_conversation_id'), table_name='booking_intents')
    op.drop_table('booking_intents')
    op.drop_index(op.f('ix_quotes_property_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_conversation_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_messages_property_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_handoffs_property_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_conversation_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_knowledge_chunks_property_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_hotel_facts_property_id'), table_name='hotel_facts')
    op.drop_table('hotel_facts')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_properties_org_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('organizations')
    # ### end Alembic commands ###
