"""simulator tables

Revision ID: def4336548cb
Revises: adcb36a4da20
Create Date: 2026-09-28 22:31:10.237419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def4336548cb'
down_revision: Union[str, Sequence[str], None] = 'adcb36a4da20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_flags',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'name')
    )
    op.create_table('sim_reservations',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('room_code', sa.String(length=40), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('quote', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('reference'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_sim_reservations_property_id'), 'sim_reservations', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_reservations_property_id'), table_name='sim_reservations')
    op.drop_table('sim_reservations')
    op.drop_table('sim_flags')
    # ### end Alembic commands ###
